using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.24.11111.11111")]
[assembly: AssemblyFileVersionAttribute("0.24.11111.11111")]
[assembly: AssemblyProductAttribute("SharpFlame")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2014")]
[assembly: AssemblyDescriptionAttribute("SharpFlame: A modern Warzone 21000 map editor based on the original Warzone 2100 " +
    "FlaME map editor.")]
[assembly: AssemblyTrademarkAttribute("MIT License")]

