using System;
using System.Reflection;
using System.Runtime.InteropServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.24.0.03")]
[assembly: AssemblyFileVersionAttribute("0.24.0.03")]
[assembly: AssemblyProductAttribute("SharpFlame")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2014 The SharpFlame Authors.")]
[assembly: AssemblyDescriptionAttribute("SharpFlame: A modern Warzone 21000 map editor based on the original Warzone 2100 FlaME map editor.")]
[assembly: AssemblyTrademarkAttribute("MIT License")]

